const screenName = {
  HOME_SCREEN: 'HOME_SCREEN',
  DETAIL_AUCTION_SCREEN: 'DETAIL_AUCTION_SCREEN',
  EXPLORE_SCREEN: 'EXPLORE_SCREEN',
  PROFILE_SCREEN: 'PROFILE_SCREEN',
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  UPLOAD_SCREEN: 'UPLOAD_SCREEN',
  BOTTOM_STACK: 'BOTTOM_STACK',
  HOME_STACK: 'HOME_STACK',
  PROFILE_STACK: 'PROFILE_STACK',
  EXPLORE_STACK: 'EXPLORE_STACK',
  AUTH_STACK: 'AUTH_STACK',
  UPLOAD_STACK: 'UPLOAD_STACK',
};

export default screenName;
