const screenName = {
  HOME_SCREEN: 'HOME_SCREEN',
  DETAIL_SOLD_SCREEN: 'DETAIL_SOLD_SCREEN',
  EXPLORE_SCREEN: 'EXPLORE_SCREEN',
  PROFILE_SCREEN: 'PROFILE_SCREEN',
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  BOTTOM_STACK: 'BOTTOM_STACK',
  HOME_STACK: 'HOME_STACK',
  PROFILE_STACK: 'PROFILE_STACK',
  EXPLORE_STACK: 'EXPLORE_STACK',
};

export default screenName;
